config/routes.rb
Rails.application.routes.draw do
root 'static_pages#home'
get '/about', to: 'static_pages#about'

resources :notes 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/note.rb
class Note < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :set_note, only: [:show, :edit, :update, :destroy]
  
  def index
    @notes = Note.all
  end

  def show
  end

  def new
    @note = Note.new
    render :form
  end

  def create
    @note = Note.new(note_params)
      if @note.save
        redirect_to note_path(@note)
      else
        render :form
      end
  end

  def edit
    render :form
  end

  def update
    if @note.update(note_params)
      redirect_to note_path(@note)
    else
      render :form
    end
  end

  def destroy
    @note.destroy
    redirect_to notes_path
  end

private

def note_params
  params.require(:note).permit(:name, :body)
end

def set_note
  @note = Note.find(params[:id])
end


end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PostItNotes</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/notes/create.html.erb
<h1>Notes#create</h1>
<p>Find me in app/views/notes/create.html.erb</p>

app/views/notes/destroy.html.erb
<h1>Notes#destroy</h1>
<p>Find me in app/views/notes/destroy.html.erb</p>

app/views/notes/form.html.erb
<%= form_for @note do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <br />
  <%= f.label :body %>
  <%= f.text_area :body %>
  <%= f.submit %>
  <% end %>

  <p>
  <%= link_to 'Home Page', root_path %>

app/views/notes/index.html.erb
<h1>Post Its</h1>
<p>
  <%= link_to 'Create New Note', new_note_path %>
</p>
<% @notes.each do |note| %>
  <h2> <%= note.name %></h2>
  <%= link_to 'Show Note', note_path(note.id) %>
  <%= link_to 'Edit Note', edit_note_path(note) %>
  <%= link_to 'Delete', note_path(note), method: :delete %>
<% end %>
</br>
</br>
</br>
<%= link_to 'Home Page', root_path %>

app/views/notes/new.html.erb
<h1>Create a Post It Note</h1>
<%= form_for @note do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <br />
  <%= f.label :body %>
  <%= f.text_area :body %>
  <%= f.submit %>
  <% end %>

  <p>
  <%= link_to 'Home Page', root_path %>
</p>

app/views/notes/show.html.erb
<h1><%=@note.name%></h1>

<p><%= @note.body %></p>

<p>
</br>
<%= link_to 'Edit Note', edit_note_path(@note) %>
</br>
<%= link_to 'Delete', note_path(@note), method: :delete %>
</br>
  <%= link_to 'Home Page', root_path %>
</p>

app/views/notes/update.html.erb
<h1>Notes#update</h1>
<p>Find me in app/views/notes/update.html.erb</p>

app/views/static_pages/about.html.erb
<h1>About Post It Notes</h1>
</br>
<p>This app allows to you create digital post it notes!</p>
</br>
<%= link_to 'Home Page', root_path %>

app/views/static_pages/home.html.erb
<h1>Welcome to the Post It Notes App!!!</h1>

<%= image_tag("post_it_pic.jpg") %>

<h2>Where would you like to go?</h2>

<%= link_to 'New Post It', new_note_path %>
</br>
<%= link_to 'See All Post Its', notes_path %>
</br>
<%= link_to 'About the app', about_path %>